"""new fields in user model

Revision ID: 986f8b703a6b
Revises: 74d8f7060fc9
Create Date: 2024-02-20 01:10:47.579765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986f8b703a6b'
down_revision = '74d8f7060fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
